name: Lint
run-name: ${{ github.workflow }}; Trigger ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - ./**/*.json
      - .stylelintrc.js
      - .stylelintignore
      - .eslintignore
      - .gitignore
      - .prettierignore
      - README.md
      - yarn.lock
      - config/**/*
      - webpack.config.ts
jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  lintTs:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use common setup
        uses: ./.github/workflows/prepare.yml
      - name: Lint TS
        run: pnpm lint:ts
  lintStyle:
    name: Lint Style
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use common setup
        uses: ./.github/workflows/prepare.yml
      - name: Lint style
        run: pnpm lint:style
