name: Lint
run-name: ${{ github.workflow }}; Trigger ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - ./**/*.json
      - .stylelintrc.js
      - .stylelintignore
      - .eslintignore
      - .gitignore
      - .prettierignore
      - README.md
      - yarn.lock
      - config/**/*
      - webpack.config.ts

jobs:
  lintTs:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    needs: prepare  # Это обозначает, что lint будет ждать завершения работы prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Prepare Environment Workflow
        uses: ./.github/workflows/prepare.yml
      - name: Lint TypeScript
        run: pnpm lint:ts
