name: Lint
run-name: ${{ github.workflow }}; Trigger ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - ./**/*.json
      - .stylelintrc.js
      - .stylelintignore
      - .eslintignore
      - .gitignore
      - .prettierignore
      - README.md
      - yarn.lock
      - config/**/*
      - webpack.config.ts

jobs:
  lintTs:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use common setup from prepare.yml
        uses: ./.github/workflows/prepare.yml  # Подключаем workflow prepare.yml

      - name: Lint TypeScript
        run: pnpm lint:ts

  lintStyle:
    name: Lint Style
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use common setup from prepare.yml
        uses: ./.github/workflows/prepare.yml  # Подключаем workflow prepare.yml

      - name: Lint Style
        run: pnpm lint:style
