name: Unit
run-name: ${{ github.workflow }}; Trigger ${{ github.ref_name }}; Runner ${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - ./**/*.json
      - .stylelintrc.js
      - .stylelintignore
      - .eslintignore
      - .gitignore
      - .prettierignore
      - README.md
      - yarn.lock
      - config/**/*
      - webpack.config.ts
jobs:
  unitTest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Use common setup
        uses: ./.github/workflows/prepare.yml
      - name: test
        run: pnpm test:unit
